# Versão do Docker Compose a ser utilizada
version: '3.8'

services:
  postgres_dw:
    image: postgres:14-alpine

    container_name: pixtur_dw_postgres

    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: pixtur_dw

    ports:
      - "5439:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

volumes:
  postgres_data:
    driver: local